### ISSUE TITLE
All the Origin Locations 

### ISSUE THREAD

**Issue by The-Naveen** [UdayKiran112/PFS_Cpp_Implementation#2]
- [ ] x
- [ ] a
- [ ] Pki
- [ ] A
- [ ] Sigma Pki
- [ ] Message
- [ ] TimeStamp
- [ ] B
- [ ] Sigma M

**Comment by KumarTeja-04** [comment]
##Answers

- [ ] x  =  TA::Constructor
- [ ] a  =  vehicle :: request Verification ->TA::validate request->TA:: signature Generation
- [ ] Pki =vehicle::Constructor->key::constructor->key::generate Public Key
- [ ] A = vehicle :: request Verification ->TA::validate request->TA:: signature Generation
- [ ] Sigma Pki =vehicle :: request Verification ->TA::validate request->TA:: signature Generation
- [ ] Message= main
- [ ] Time Stamp = vehicle::sign Message::Constructor
- [ ] B = vehicle:: sign Message 
- [ ] Sigma M = Vehicle :: Signed Message

**Comment by The-Naveen** [comment]
Looks Perfect
